version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: nestjs
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres:
